### ISSUE TITLE
compiz-earth-0.8 compile error

### ISSUE THREAD

**Issue by Eignar17** [matijaskala/compiz-earth#1]
Package compiz-gconf was not found in the pkg-config search path.
Perhaps you should add the directory containing `compiz-gconf.pc'
to the PKG_CONFIG_PATH environment variable
No package 'compiz-gconf' found
compiling : earth.c -> build/earth.loearth.c: In function ‘earthInitScreen’:
earth.c:338:39: error: too few arguments to function ‘mkdir’
     if ((stat (imagedir, &st) < 0 && (mkdir (imagedir) < 0 || stat (imagedir, &
                                       ^
In file included from earth.h:12:0,
                 from earth.c:1:
/usr/include/x86_64-linux-gnu/sys/stat.h:320:12: note: declared here
 extern int mkdir (const char *__path, __mode_t __mode)
            ^
Makefile:284: fallo en las instrucciones para el objetivo 'build/earth.lo'
make: *** [build/earth.lo] Error 1

**Comment by matijaskala** [comment]
Sorry, I forgot mkdir takes 2 arguments.
Should be fixed by a23f33d8f602ade5b841209dfbd6817787f0d3a0

**Comment by soreau** [comment]
I notice the code assumes ~/.compiz/data/ exists as well.. can you whip up a patch to mkdir for this one too @matijaskala ?

**Comment by matijaskala** [comment]
@soreau wouldn't both of these two cases cause problems?
- `~/.compiz/data/` doesn't exist
- `~/.compiz/data/` exists but it's empty

I mean, the code assumes that the shaders exist, not just the directory. I'm not sure whether compiz can handle nonexisting files or should the plugin do this.

**Comment by soreau** [comment]
Yes, you're right. Really we should just use DATADIR which is defined by the Makefile. It will be ~/.compiz/data for locally installed plugins and $prefix/share/compiz for global installation. The installation should install the files to the correct location and we shouldn't crash if the shaders don't exist.

**Comment by soreau** [comment]
The only reason we're using ~/.compiz/images/ directly for the clouds texture is because we need a place that the user is guaranteed to have write access.
