### ISSUE TITLE
error compiz earth 0.8  + cube reflection and deformation plugin conflict

### ISSUE THREAD

**Issue by Eignar17** [matijaskala/compiz-earth#2]
![screenshot at 2017-04-12 21 57 22](https://cloud.githubusercontent.com/assets/8561550/24988492/ec332ad2-1fcb-11e7-8f0e-ebe15815f575.png)

conflict bugs it freezes

**Comment by matijaskala** [comment]
Try now, after 96433dc49fdfc68468297b25f6a9f9ca104090ff

**Comment by soreau** [comment]
That isn't the problem. We can make the two mutually exclusive using metadata, by putting an <feature>atmosphere</feature> tag, like cube and wall do with largedesktop. Nice find.

**Comment by Eignar17** [comment]
My compile 
Package compiz-gconf was not found in the pkg-config search path.
Perhaps you should add the directory containing `compiz-gconf.pc'
to the PKG_CONFIG_PATH environment variable
No package 'compiz-gconf' found
convert   : earth.xml.in -> build/earth.xml
bcop'ing  : build/earth.xml -> build/earth_options.h
bcop'ing  : build/earth.xml -> build/earth_options.c
compiling : earth.c -> build/earth.lo
compiling : build/earth_options.c -> build/earth_options.lo
linking   : build/libearth.laar: `u' modifier ignored since `D' is the default (see `U')
linking   : build/libearth.la
Package compiz-gconf was not found in the pkg-config search path.
Perhaps you should add the directory containing `compiz-gconf.pc'
to the PKG_CONFIG_PATH environment variable
No package 'compiz-gconf' found
install   : /home/eignar/.compiz/plugins/libearth.so
install   : /home/eignar/.compiz/metadata/earth.xml
install   : /home/eignar/.compiz/data/earth.vert
install   : /home/eignar/.compiz/data/earth.frag
install   : /home/eignar/.compiz/images/clouds.png
install   : /home/eignar/.compiz/images/day.png
install   : /home/eignar/.compiz/images/night.png
install   : /home/eignar/.compiz/images/skydome.png

**Comment by Eignar17** [comment]
perfect :3 
![screenshot at 2017-04-13 20 37 02](https://cloud.githubusercontent.com/assets/8561550/25030190/fd24b172-2088-11e7-8091-2eb81386e291.png)
